"""adiciona descricao em produtos

Revision ID: f9aa03b4702f
Revises: a68c5958d1e7
Create Date: 2026-08-24 15:47:37.771452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9aa03b4702f'
down_revision: Union[str, Sequence[str], None] = 'a68c5958d1e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('descricao', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'descricao')
    # ### end Alembic commands ###
